### ISSUE TITLE
Feature Request: Add Nerd Font Support

### ISSUE THREAD

**Issue by humanbeeng** [zed-industries/zed-fonts#10]
Loving this font. Unfortunately I can't use this font in Neovim due to lack of Nerd Font. Please consider releasing a nerd font version. Thanks

**Comment by nferhat** [comment]
You can either:

- Use an Iosevka Nerd Font build (since Zed Mono is basically the same with some patches)
- Patch Zed Mono (See https://github.com/ryanoasis/nerd-fonts#font-patcher)

**Comment by iamnbutler** [comment]
Feel free to add a PR with the patched version & instructions :)

**Comment by iamnbutler** [comment]
Sure - go for it 😊

**Comment by danielzsh** [comment]
Any updates on this? No nerd fonts are making my terminal prompt unusable 😅

**Comment by karimbenbourenane** [comment]
I created a tap and formula for this. You can install Zed Mono patched with Nerd Font using homebrew on macOS with the following:

`brew tap karimbenbourenane/cask-fonts`
`brew install font-zed-mono-nerd-font`

These fonts have been patched with the `--complete` flag used by the docker method of font patching. And it includes all the font styles, so the font package is quite large when being installed by `brew`.

I hope this helps for those that use macOS and want to incorporate the Zed Mono font with the terminal.

Remember that Zed settings will need to be modified to include the following in the root configuration object to enable nerd fonts on the terminal:
`"terminal": { "font_family": "ZedMono Nerd Font" }`

**Comment by danielzsh** [comment]
Just a quick note, this nerd font appears to be missing the up arrow indicator used to denote `push`:
<img width="1015" alt="image" src="https://github.com/zed-industries/zed-fonts/assets/65467530/92ddcdc1-269d-4f7c-90f3-ab71f7d493f3">

**Comment by Finii** [comment]
> Hoping they can merge it soon.

Ready to merge flag set. Nerd Font release will be the next days.

@karimbenbourenane 
> `brew install font-zed-mono-nerd-font`

Well, that will clash with the official Nerd Font cask :unamused: 
How shall we fix that?

**Comment by Finii** [comment]
Hmm, I can not find the cask (luckily)

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/9108307c-ca03-4908-9c29-7f99e8a583d8)

Ah now I see it, it is @karimbenbourenane own tap.

> `brew tap karimbenbourenane/cask-fonts`

Sorry I was too dumb. All good!

**Comment by karimbenbourenane** [comment]
> Just a quick note, this nerd font appears to be missing the up arrow indicator used to denote `push`: <img alt="image" width="1015" src="https://private-user-images.githubusercontent.com/65467530/318201823-92ddcdc1-269d-4f7c-90f3-ab71f7d493f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MjEyNTQsIm5iZiI6MTcxMTkyMDk1NCwicGF0aCI6Ii82NTQ2NzUzMC8zMTgyMDE4MjMtOTJkZGNkYzEtMjY5ZC00ZjdjLTkwZjMtYWI3MWY3ZDQ5M2YzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDIxMzU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzN2I2YjM5ZmNkODAzYzg3OThkMjMxMjIzNmEyN2MxNTYzOTM0NTA4YjM4MjMzZTIyZWNkNjBjZWIyZTMwMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j3MpQabbAuVqCRSb7s1eyycVpAWEYvXDlnhQGGsnnNY">

I'm not sure what that glyph is supposed to look like, can you give an example? Also when the official nerd font release comes out I can remove mine from my tap, I did this just as a temporary solution until then (I didn't realize it's coming out in just a few days).

**Comment by Finii** [comment]
> I didn't realize it's coming out in just a few days

Even for me its always a surprise if it comes out 'on time' :smile: Given that I 'determine' the next release date half a year in advance and it is just a hobby.

The 'up' arrow is probably `↑`

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/62cd08d4-640f-4f7a-a9a7-f677e119367c)

which is codepoint `2191` and not a Nerd Font patched glyph.

See some other examples in the images in [this comment](https://github.com/ryanoasis/nerd-fonts/pull/593#issuecomment-801270215)

Hmm, but it's there :thinking: 

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/fb66c78c-755b-46d2-b6be-6f44270ddb45)

:woman_shrugging: 

But these is another problem with patching

```
Done with Patch Sets, generating font...
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph HEAVY making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph POWER making the whole subtable invalid
Lookup subtable contains unused glyph HEAVY making the whole subtable invalid
   ZedMono Nerd Font
   \===> 'ZedMonoNerdFont-Regular.ttf'
```

**Comment by karimbenbourenane** [comment]
Hmm.. so is there anything I can actually do to get that glyph into my Zed Mono patched fonts? I used the `--complete` flag running the Nerd Font patcher in its docker container, so I'm unsure how I'd solve this problem of that glyph being absent.

**Comment by Finii** [comment]
I guess Daniel needs to copy and paste the glyph so that we can look up its codepoint. There is most likely nothing wrong with your patch (and if there is a problem its most likely someting Nerd Fonts needs to fix). I expect the missing glyph to be no Nerd Font patched in codepoint; several "Powerlines" and stuff depend on icons that are not part of the patchset.
And/or Daniel uses a pre Nerd Fonts v3 codepoint that has been dropped.

**Comment by Finii** [comment]
Baah... `fontforge` bites us again :-(

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/3b6e023d-86b7-46a1-8479-9a930cdc725d)

Not that I had not fixed several of these problems in ff already. This might take a while, I will report the progress only in the NF Issue (see above) to not spam zed users.

**Comment by danielzsh** [comment]
> I'm not sure what that glyph is supposed to look like, can you give an example? Also when the official nerd font release comes out I can remove mine from my tap, I did this just as a temporary solution until then (I didn't realize it's coming out in just a few days).

Here's how it looks in JetBrains Mono (as you can see, it's now positioned much better within the brackets):

<img width="185" alt="image" src="https://github.com/zed-industries/zed-fonts/assets/65467530/b0baba53-4352-48b1-a488-f53ae746bb91">

And the actual glyph itself is ⇡

**Comment by Finii** [comment]
That is `21E1`

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/8e3e4301-e3ae-40c1-8018-db958a49a3f2)

Which is in the font

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/286dcae8-9482-4b4d-9c27-7364bcd5d66f)

Hmm, and there is a lookup table...

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/bfe4b11b-133f-45a0-beb8-9c6b9a1ec3a8)

But that glyph is also ok:

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/a4be8120-3a6f-41aa-9ee9-e14c218cf35e)

Maybe that is because `fontforge` breaks the subtables. Will investigate later.

**Comment by Finii** [comment]
This looks fishy...

`21E1` is `uni21E1` will be replaced by `uni21E1.NWID` which will be replaced by `uni21E1`, which will be ... etc (loop?!)

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/6641a4df-9cb3-4ec5-8056-d1be73f50a6c)

**Comment by danielzsh** [comment]
The glyph renders oddly in unpatched Iosevka as well, it might just be an issue with Iosevka then?

**Comment by Finii** [comment]
Can you try this patch?

[IosevkaNerdFont-Regular.ttf.zip](https://github.com/zed-industries/zed-fonts/files/14826470/IosevkaNerdFont-Regular.ttf.zip)

**Comment by danielzsh** [comment]
It's still rendering like this for me:
<img width="490" alt="image" src="https://github.com/zed-industries/zed-fonts/assets/65467530/aee4d14f-a509-485d-938d-6205efd6960a">

(btw, I noticed that character width is no longer as large as Zed Mono, is this intended?)

**Comment by Finii** [comment]
Thanks for testing!
The character width is just what ordinary Iosevka has. The only thing I changed is removing the double-width arrows.

Hmm, the arrow seems to be the `uni21E2.WWID` :thinking: (which is 2 cells wide)

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/547083a9-1ddd-4c7b-a1ed-91982c4b6001)

Ah, I removed the NWID (narrow character) to WWID (wide character) rule, but the WWID are already the standard variant.

We already had that at Nerd Fonts as Issue (without solution), let me think a bit.

**Comment by Finii** [comment]
Ok, this is all working as intended by Iosevka and/or the person who created the build plan for Zed-Mono.

The dashed-up-arrow is supposed two be two cells wide.

If you do not want that, change the Zed build plan like this:

```diff
--- a/private-build-plans.toml
+++ b/private-build-plans.toml
@@ -7,9 +7,10 @@
 
 [buildPlans.zed-mono]
 family = "Zed Mono"
-spacing = "normal"
+spacing = "term"
 serifs = "sans"
 no-cv-ss = false
 
   [buildPlans.zed-mono.variants]
   inherits = "ss08"
```

When Zed updates to a newer upstream (i.e. Iosevka) the better build instruction could be `enableNwidWwid = false` but that is not available yet in Zed's Iosevka.

I believe this change should be applied to the Zed repo here, but then, I do not know what the authors intend.
Maybe you want to raise an Issue. But then, that directly opposes this information about Zed Version 1.1.0 (from the CHANGELOG):
> ## Version 1.1.0
> Updated build plans – Mono and Sans now build with the same characters, weights and widths

The Sans should probably keep the 2 cell wide up-arrow, but for term it is problematic, but someone decided to have all width the same :woman_shrugging: 

_This is not my expertise, the information in this comment might or might not be correct._

**Comment by Finii** [comment]
Ah here, the documentation snipped, forgot that:

![image](https://github.com/zed-industries/zed-fonts/assets/16012374/1a298442-6e9e-4dcd-83c2-f387ecf76e58)

https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md#configuring-custom-build

**Comment by Finii** [comment]
https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.0

**Comment by Finii** [comment]
@karimbenbourenane 
https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-zed-mono-nerd-font.rb

**Comment by karimbenbourenane** [comment]
@Finii Thanks for getting this into homebrew, I'm now going to go delete my repo and tap. Good work!

**Comment by Finii** [comment]
Just wanted to add that Nerd Fonts does not include all weights, I think `thin` and `extra-light` has been omitted for being not useful for terminal use (maybe).

**Comment by Afrowave** [comment]
Beautiful work. Thanks guys.👏🏾
