### ISSUE TITLE
Vs Code not recognizing Zed Mono Extended

### ISSUE THREAD

**Issue by chcg823** [zed-industries/zed-fonts#13]
- I tried changing the font to `Zed Mono Extended` but VS Code is not detecting it and uses the fallback font.

- When I tried to use `Zed Mono Light` and `Zed Mono` they are working fine.

- Operating System - Windows 11

1. Using Zed Mono - 
![image](https://github.com/zed-industries/zed-fonts/assets/46193776/37e52ec1-56d5-4436-8c94-18120f5728e9)

2. Using Zed Mono Light - 
![image](https://github.com/zed-industries/zed-fonts/assets/46193776/770534a0-a572-4f38-a3a7-6162e16e80f1)

3. Using Zed Mono Extend - 
![image](https://github.com/zed-industries/zed-fonts/assets/46193776/306de34f-7bc4-4fbc-bc62-4749d21a61ae)

**Comment by evan-buss** [comment]
Since Zed is based on Iosevka, [this](https://github.com/be5invis/Iosevka/issues/426#issuecomment-643622855) solution works. I was able to get it working with `Zed Mono Expanded`.

**Comment by chcg823** [comment]
Hey @evan-buss,
Thanks for the resolution. It is working now.
I hope someone adds it to the README.

**Comment by aviadhaham** [comment]
Seems like the issue returned, and the workaround isn't working with the "Expanded" :(

**Comment by craftogrammer** [comment]
> Seems like the issue returned, and the workaround isn't working with the "Expanded" :(

Strange but it is working for me on latest Vscode.

```
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
```
![image](https://github.com/user-attachments/assets/595b8114-9b1a-448d-92df-067a55daca69)
