### ISSUE TITLE
How can I turn off ligatures?

### ISSUE THREAD

**Issue by msal4** [zed-industries/zed-fonts#14]
I'm using kitty and I don't believe the font is displaying ligatures correctly
<img width="490" alt="image" src="https://github.com/zed-industries/zed-fonts/assets/30052233/8ef7eb8f-a6a4-43ff-90bc-ccb0bb4132dd">

I don't want ligatures anyhow and I'll be fine without them, I just have no idea how to disable them, do i have to do it when building the font?

**Comment by iamnbutler** [comment]
IIRC this should be based on the open type settings config – does Kitty allow you to customize those? Ligatures are not hard coded to be on, they are an open type feature AFAIK

**Comment by iamnbutler** [comment]
Err my apologies, looking at this PR maybe there is a way to build without ligatures: https://github.com/zed-industries/zed-fonts/pull/8/files

Maybe try using that buildplan and see if it works?

**Comment by iamnbutler** [comment]
I've merged that PR, try building it and see if that works. At some point I'll rebuild and add a new release. Feel free to re-open if this doesn't fix the issue.

**Comment by msal4** [comment]
perfect! thanks :)
