### ISSUE TITLE
Investigate enabling `export-glyph-names` for Kitty, other tools that need glyph names

### ISSUE THREAD

**Issue by stickyburn** [zed-industries/zed-fonts#2]
Started using this awesome font on my terminal but the ligature for -> is displaying incorrectly. Not sure if it's my terminal or the font, as my terminal works well with other fonts, and Zed Mono works well in other places like the IDE :thinking: 

Current view
![image](https://user-images.githubusercontent.com/37672190/191714956-6ef76e23-2593-4c97-ae61-54973b667664.png)

Expected view
![image](https://user-images.githubusercontent.com/37672190/191715250-24f8d6c9-047b-4f35-a347-dd2e65d566be.png)

Terminal - Kitty
OS - Artix Linux
Font - Zed Mono

**Comment by jakobbouchard** [comment]
they'll need to enable the `export-glyph-names` option in their custom build for it to work in Kitty. See the [Iosevka repo for info](https://github.com/be5invis/Iosevka/blob/main/doc/custom-build.md#configuring-custom-build)

**Comment by yashank09** [comment]
@jakobbouchard for sure!! I wonder if there's a way to enable this ourselves?

**Comment by jakobbouchard** [comment]
You could pull the repo and build it yourself :) I actually ended up making my own custom build in the end, so you might end up down that rabbit hole too hahaha

**Comment by yashank09** [comment]
Thanks for the tip! Looks like my next weekend is now full 😅

**Comment by yashank09** [comment]
Ill leave this open incase there's native support anytime

**Comment by iamnbutler** [comment]
Apologies, I never saw this issue 🙏🏽 I'll try to add this the next time we do a release of the font. I plan on doing some subsetting to reduce the size of each weight soon, so I can try to roll this in at the same time.

**Comment by stickyburn** [comment]
@iamnbutler Was this ever added? If so we can close this :smile:
