### ISSUE TITLE
Nerd Font

### ISSUE THREAD

**Issue by Kamek437** [zed-industries/zed-fonts#21]
Any chance we could get icons in the font like nerd fonts or powerline fonts? I'd use it on my terminal but I need icons and stuff. There's a way in most terms to set an alternative symbol font but that hasn't worked for me does anyone else have any ideas? I realize this might be a big ask as fonts are complex but figured I'd at least ask. Love Zed, best editor ever!

**Comment by c4710n** [comment]
Nerd Fonts has a patched ZedMono now. Checkout https://www.nerdfonts.com/font-downloads

**Comment by Kamek437** [comment]
Awsome, thanks dude.
