### ISSUE TITLE
Crowded spacing for nerd fonts 

### ISSUE THREAD

**Issue by B4Dmonkey** [zed-industries/zed-fonts#23]
it seems that theres a bit of overlap when using nerd font for the terminal. the slash is very close to the apple symbol. Even when zoomed in this stills apears.

<img width="298" alt="image" src="https://github.com/user-attachments/assets/7cc924d9-586a-4f65-a6b5-4df708eb80dc">

**Comment by notpeter** [comment]
If you're using the Nerd Font patched version of Zed Mono and are reporting an issue with those added glyphs, you should probably report that to their repo: https://github.com/ryanoasis/nerd-fonts/issues.
