### ISSUE TITLE
feature request: no ligatures version

### ISSUE THREAD

**Issue by c4710n** [zed-industries/zed-fonts#7]
Thanks for this great font.

How about a no ligatures version for Zed Mono. It would be nice to have this because some softwares can't disable it, such as Xcode.

Related links:
+ https://github.com/JetBrains/JetBrainsMono/issues/19 - previously, Jetbrains Mono has this problem, too. Then, they provided a NL version.

**Comment by iamnbutler** [comment]
PR is merged – feel free to build from source. Eventually I'll do a new release build.
